checks:
- type: shell
  name: ls verification
  frequency: 100 # seconds
  config:
    command: "ls"
    args:
    - "-lh"
- type: shell
  name: pwd
  frequency: 200
  config:
    command: "pwd"
    args: []
- type: shell
  name: sleep
  frequency: 50
  config:
    command: "sleep"
    args: ["5"]
- type: http
  name: http 200
  frequency: 10
  config:
    host: "httpstat.us"
    path: "/200"
    scheme: "https"
    method: get
- type: http
  name: http 500
  frequency: 10
  config:
    host: "httpstat.us"
    path: "/500"
    scheme: "https"
    method: get
- type: http
  name: http timeout
  frequency: 20
  config:
    host: "httpstat.us"
    path: "/200?sleep=30000"
    scheme: "https"
    method: get